####
POST http://localhost:3030/songs HTTP/1.1
Content-Type: application/json

{
  "title": "cuacamayo",
  "interpreter": "danit",
  "year": 2020,
  "imgurl": "https://static.nationalgeographic.es/files/styles/image_3200/public/2242.600x450.jpg?w=710&h=533"
}

###
GET http://localhost:3030/songs HTTP/1.1

###
GET http://localhost:3030/songs/63f54a576e596bf6b33c65b7 HTTP/1.1

###
PUT http://localhost:3030/songs/63f613d504e9e89a56234dbe HTTP/1.1
Content-Type: application/json


{
    "title": "guacamayo",
  "interpreter": "Danit",
   "year": 2020,
    "imgurl": "https://static.nationalgeographic.es/files/styles/image_3200/public/2242.600x450.jpg?w=710&h=533"

}

###
DELETE http://localhost:3030/songs/63f58012fdec4269e5837000 HTTP/1.1
